[project]
name = "WikidataTextifier"
version = "0.1.0"
description = "Transforms Wikidata entities into text representations."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "sqlalchemy>=2.0.41",
]
